"""Removed content from documents

Revision ID: cd4104f02be8
Revises: fca222003b26
Create Date: 2026-03-08 06:05:49.485529
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "cd4104f02be8"
down_revision: Union[str, None] = "fca222003b26"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("current_version_id", sa.Uuid(), nullable=False)
    )
    op.create_foreign_key(
        None, "documents", "document_versions", ["current_version_id"], ["id"]
    )
    op.drop_column("documents", "content")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "documents", sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True)
    )
    op.drop_constraint(None, "documents", type_="foreignkey")
    op.drop_column("documents", "current_version_id")
    # ### end Alembic commands ###
