"""Changed backe to UTC and added Column DATETIME in created and updated

Revision ID: fca222003b26
Revises: 52818e3b5702
Create Date: 2026-03-04 15:40:38.172369
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "fca222003b26"
down_revision: str | None = "52818e3b5702"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
