"""Changed backe to UTC and added Column DATETIME in created and updated

Revision ID: fca222003b26
Revises: 52818e3b5702
Create Date: 2026-03-04 15:40:38.172369
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fca222003b26"
down_revision: Union[str, None] = "52818e3b5702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
