"""Changed from UTC to timezone.utc in created and updated

Revision ID: 30736f246a8b
Revises: 8d976c30022d
Create Date: 2026-03-04 12:37:47.395240
"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "30736f246a8b"
down_revision: str | None = "8d976c30022d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
